const NETWORK_KEYS = {
  bibus: 'NOTION_DS_BIBUS', lemet: 'NOTION_DS_LEMET', yelo: 'NOTION_DS_YELO', ocecars: 'NOTION_DS_OCECARS', tfl: 'NOTION_DS_TFL', qub: 'NOTION_DS_QUB',
};
const DATA_SOURCE_FALLBACKS = {
  bibus: '36493645-8361-81d5-aa65-000bfc2254ec', lemet: '36493645-8361-8151-8160-000bb2a95b4b', yelo: '3b593645-8361-8001-9b66-000b6f3f55ab', ocecars: '3c193645-8361-80f4-84d7-000b045752c6', tfl: '37293645-8361-81c0-8ebd-000bb403afce', qub: 'b0c93645-8361-8253-b5c8-872462a4c678',
};
const MAX_NOTION_REQUESTS_PER_INVOCATION = 45;

function textProperty(p){if(!p)return '';if(p.type==='title')return p.title?.map(x=>x.plain_text).join('')||'';if(p.type==='rich_text')return p.rich_text?.map(x=>x.plain_text).join('')||'';if(p.type==='select')return p.select?.name||'';if(p.type==='status')return p.status?.name||'';if(p.type==='number')return p.number??'';if(p.type==='date')return p.date?.start||'';if(p.type==='url')return p.url||'';if(p.type==='checkbox')return p.checkbox?'Oui':'Non';return '';}
function first(props,names){for(const name of names){if(props[name]){const value=textProperty(props[name]);if(value!=='')return value;}}return '';}
function linkProperty(p){if(!p)return '';if(p.type==='url')return p.url||'';if(p.type==='rich_text'){const item=p.rich_text?.find(x=>x.href||x.text?.link?.url);return item?.href||item?.text?.link?.url||'';}return '';}
function firstLink(props,names){for(const name of names){const value=linkProperty(props[name]);if(value)return value;}return '';}
function imageProperty(p){if(!p||p.type!=='files')return '';const file=p.files?.[0];return file?.external?.url||file?.file?.url||'';}
function pageCover(page){const cover=page?.cover;if(!cover)return '';if(cover.type==='external')return cover.external?.url||'';if(cover.type==='file')return cover.file?.url||'';return '';}
function normalize(page,network){const p=page.properties||{};const arrival=first(p,["Date d'arrivée","Date d’arrivee","Arrivée sur le réseau","Date d'arrivée sur le réseau","Entrée sur le parc"]);const circulation=first(p,['Mise en circulation','Date de mise en circulation']);const common={id:page.id,network,notionUrl:page.url||'',tcInfosUrl:firstLink(p,['TC Infos','Source TC Infos','Fiche détaillée TC Infos','Lien TC Infos','TC Infos URL']),fotobusUrl:firstLink(p,['Fotobus','Fiche Fotobus','URL Fotobus','Fotobus URL','Source Fotobus']),arrivalDate:arrival,arrivalDateEstimated:Boolean(first(p,["Date d'arrivée estimée"]))};const coverImage=pageCover(page);if(network==='tfl')return {...common,park:String(first(p,['Fleet Number'])||'—'),registration:String(first(p,['Registration Number'])||'—'),brand:String(first(p,['Chassis Make and Model  ','Chassis Make and Model'])||'—'),model:String(first(p,['Body Make and Model'])||'—'),type:String(first(p,['Bus Type ','Bus Type'])||'—'),date:String(circulation||''),status:'En service',image:coverImage||imageProperty(p['Fichiers et médias'])||imageProperty(p['Photo de couverture'])||imageProperty(p['Photo'])||''};return {...common,park:String(first(p,['No de parc','No de Parc','Numéro de parc','Parc','Numéro'])||'—'),registration:String(first(p,['Immatriculation','Immatriculation '])||'—'),brand:String(first(p,['Constructeur','Marque'])||'—'),model:String(first(p,['Modèle','Modele'])||'—'),type:String(first(p,['Bus ou Tramway','Type','Type de véhicule'])||'—'),date:String(arrival||circulation||''),status:String(first(p,['Statut TC Infos','Statut TC Info','Statut','État'])||'En service'),image:coverImage||imageProperty(p['Photo de couverture'])||imageProperty(p['Photo'])||imageProperty(p['Fichiers et médias'])||''};}
function notionValue(type,value,definition){if(value===undefined||value===null||value==='')return null;if(type==='title')return{title:[{type:'text',text:{content:String(value)}}]};if(type==='rich_text')return{rich_text:[{type:'text',text:{content:String(value)}}]};if(type==='url')return{url:String(value)};if(type==='date')return{date:{start:String(value)}};if(type==='checkbox')return{checkbox:Boolean(value)};if(type==='number'){const n=Number(value);return Number.isFinite(n)?{number:n}:null;}if(type==='select'){const options=definition?.select?.options||[];return options.some(o=>o.name===String(value))?{select:{name:String(value)}}:null;}if(type==='status'){const options=definition?.status?.options||[];return options.some(o=>o.name===String(value))?{status:{name:String(value)}}:null;}return null;}
function normalizeName(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');}
function findProperty(schema,names,type){const entries=Object.entries(schema||{});const wanted=names.map(normalizeName);let found=entries.find(([name,p])=>wanted.includes(normalizeName(name))&&(!type||p.type===type));if(found)return found;found=entries.find(([name,p])=>wanted.includes(normalizeName(name)));return found||null;}
function findTitleProperty(schema){return Object.entries(schema||{}).find(([,p])=>p.type==='title')||null;}
function addMapped(properties,schema,names,value){if(value===undefined||value===null||value==='')return;const entry=findProperty(schema,names);if(!entry)return;const [name,definition]=entry;const prop=notionValue(definition.type,value,definition);if(prop)properties[name]=prop;}
async function notionRequest(url,token,options={}){const response=await fetch(url,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','Notion-Version':'2025-09-03',...(options.headers||{})}});const body=await response.text();let parsed=null;try{parsed=JSON.parse(body);}catch{}if(!response.ok){const error=new Error(parsed?.message||parsed?.code||body||`Notion returned ${response.status}`);error.notionStatus=response.status;error.notionCode=parsed?.code||'';throw error;}return parsed;}
async function getDataSource(dataSourceId,token){return notionRequest(`https://api.notion.com/v1/data_sources/${dataSourceId}`,token);}
async function queryDataSource(dataSourceId,token,initialCursor){const result=[];let start_cursor=initialCursor||null;let requests=0;let has_more=false;let next_cursor=null;while(requests<MAX_NOTION_REQUESTS_PER_INVOCATION){const data=await notionRequest(`https://api.notion.com/v1/data_sources/${dataSourceId}/query`,token,{method:'POST',body:JSON.stringify({page_size:100,...(start_cursor?{start_cursor}:{})})});requests+=1;result.push(...(data.results||[]));has_more=Boolean(data.has_more);next_cursor=data.next_cursor||null;if(!has_more||!next_cursor)break;start_cursor=next_cursor;}return{pages:result,has_more,next_cursor,requests};}
function buildProperties(input,network,schema){const properties={};const titleEntry=findTitleProperty(schema);const title=input.park||input.registration||`${input.brand||''} ${input.model||''}`.trim()||'Véhicule sans numéro';if(titleEntry){const [name,definition]=titleEntry;properties[name]=notionValue('title',title,definition);}addMapped(properties,schema,['Immatriculation','Registration Number'],input.registration);addMapped(properties,schema,['No de parc','No de Parc','Numéro de parc','Parc','Numéro','Fleet Number'],input.park);addMapped(properties,schema,['Constructeur','Marque','Chassis Make and Model'],input.brand);addMapped(properties,schema,['Modèle','Modele','Body Make and Model'],input.model);addMapped(properties,schema,['Type','Type de véhicule','Bus ou Tramway','Bus Type'],input.type);addMapped(properties,schema,["Date d'arrivée","Date d’arrivee","Arrivée sur le réseau","Date d'arrivée sur le réseau","Entrée sur le parc"],input.arrivalDate);addMapped(properties,schema,['Mise en circulation','Date de mise en circulation'],input.circulationDate);addMapped(properties,schema,["Date d'arrivée estimée",'Date d’arrivée estimée'],Boolean(input.arrivalEstimated));addMapped(properties,schema,['Statut TC Infos','Statut TC Info','Statut','État'],input.status||'En service');addMapped(properties,schema,['Energie','Énergie'],input.energy);addMapped(properties,schema,['Exploitant','Operator'],input.operator);addMapped(properties,schema,['Dépôt','Depot'],input.depot);addMapped(properties,schema,['Dernière affectation','Derniere affectation'],input.assignment);addMapped(properties,schema,['Numéro de série','Numero de serie','Serial Number'],input.serial);addMapped(properties,schema,['Longueur','Length'],input.length);addMapped(properties,schema,['Places','Capacité','Capacite','Seats'],input.seats);addMapped(properties,schema,['Portes','Doors'],input.doors);addMapped(properties,schema,['Moteur','Engine'],input.engine);addMapped(properties,schema,['Boite de vitesse','Boîte de vitesse','Gearbox'],input.gearbox);addMapped(properties,schema,['Norme Euro','Euro'],input.euro);addMapped(properties,schema,['Climatisation','Air conditioning'],input.airConditioning);addMapped(properties,schema,['Livrée','Liverée','Livery'],input.livery);addMapped(properties,schema,['TC Infos','Source TC Infos','Fiche détaillée TC Infos','Lien TC Infos','TC Infos URL'],input.tcInfosUrl);addMapped(properties,schema,['Fotobus','Fiche Fotobus','URL Fotobus','Fotobus URL','Source Fotobus'],input.fotobusUrl);addMapped(properties,schema,['Détails TC Infos','Détails','Notes','Details'],input.details);addMapped(properties,schema,['Historique mouvements','Historique','History'],input.history);return properties;}
export async function onRequestGet({request,env}){const url=new URL(request.url);const network=url.searchParams.get('network')||'';const cursor=url.searchParams.get('cursor')||'';const envName=NETWORK_KEYS[network];if(!envName)return new Response(JSON.stringify({error:'Unknown network'}),{status:400,headers:{'content-type':'application/json'}});const dataSourceId=env[envName]||DATA_SOURCE_FALLBACKS[network];if(!dataSourceId||!env.NOTION_TOKEN)return new Response(JSON.stringify({error:'Notion is not configured on Cloudflare yet.',missing:!env.NOTION_TOKEN?'NOTION_TOKEN':envName}),{status:503,headers:{'content-type':'application/json'}});try{const{pages,has_more,next_cursor,requests}=await queryDataSource(dataSourceId,env.NOTION_TOKEN,cursor);const vehicles=pages.map(page=>normalize(page,network));vehicles.sort((a,b)=>{const da=a.arrivalDate||a.circulationDate||a.date||'';const db=b.arrivalDate||b.circulationDate||b.date||'';if(!da&&!db)return 0;if(!da)return 1;if(!db)return-1;return db.localeCompare(da);});return new Response(JSON.stringify({network,count:vehicles.length,vehicles,has_more,next_cursor,requests}),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});}catch(error){return new Response(JSON.stringify({error:'Unable to read Notion',details:error instanceof Error?error.message:String(error),notionStatus:error?.notionStatus||null,notionCode:error?.notionCode||null}),{status:502,headers:{'content-type':'application/json; charset=utf-8'}});}}
export async function onRequestPost({request,env}){const network=new URL(request.url).searchParams.get('network')||'';const envName=NETWORK_KEYS[network];const dataSourceId=envName?(env[envName]||DATA_SOURCE_FALLBACKS[network]):null;if(!envName||!dataSourceId)return new Response(JSON.stringify({error:'Unknown network'}),{status:400,headers:{'content-type':'application/json'}});if(!env.NOTION_TOKEN)return new Response(JSON.stringify({error:'Notion is not configured on Cloudflare yet.'}),{status:503,headers:{'content-type':'application/json'}});try{const input=await request.json();const registration=String(input.registration||'').trim();const park=String(input.park||'').trim();if(!registration&&!park)return new Response(JSON.stringify({error:'Immatriculation ou numéro de parc obligatoire.'}),{status:400,headers:{'content-type':'application/json'}});const existing=await queryDataSource(dataSourceId,env.NOTION_TOKEN,null);const normalizedReg=registration.replace(/\s+/g,'').toUpperCase();const duplicate=existing.pages.find(page=>{const p=page.properties||{};const r=first(p,['Immatriculation','Registration Number']).replace(/\s+/g,'').toUpperCase();const n=first(p,['No de parc','No de Parc','Numéro de parc','Parc','Numéro','Fleet Number']).trim();return(normalizedReg&&r===normalizedReg)||(park&&n===park);});if(duplicate)return new Response(JSON.stringify({error:'Ce véhicule existe déjà dans Notion.',page:normalize(duplicate,network)}),{status:409,headers:{'content-type':'application/json; charset=utf-8'}});const source=await getDataSource(dataSourceId,env.NOTION_TOKEN);const schema=source.properties||{};const properties=buildProperties(input,network,schema);if(!Object.keys(properties).length)throw new Error('Aucune propriété compatible trouvée dans la base Notion.');const data=await notionRequest('https://api.notion.com/v1/pages',env.NOTION_TOKEN,{method:'POST',body:JSON.stringify({parent:{type:'data_source_id',data_source_id:dataSourceId},properties})});return new Response(JSON.stringify({ok:true,vehicle:normalize(data,network)}),{status:201,headers:{'content-type':'application/json; charset=utf-8'}});}catch(error){return new Response(JSON.stringify({error:'Impossible d’ajouter le véhicule à Notion.',details:error instanceof Error?error.message:String(error),notionStatus:error?.notionStatus||null,notionCode:error?.notionCode||null}),{status:502,headers:{'content-type':'application/json; charset=utf-8'}});}}
